movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name="add_movie"),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/', views.delete, name="delete"),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.DateField()
    img = models.ImageField(upload_to="Gallery")

    def __str__(self):
        return '{}'.format(self.name)

movieproject/movieapp/forms.py
from .models import Movie
from django import forms


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()

    return render(request, 'index.html', {'movie_list': movie})


def detail(request, movie_id):
    cini = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'cini': cini})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name1', '')
        desc = request.POST.get('name2', '')
        year = request.POST.get('name3', '')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, "add.html")


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "edit.html", {'form': form}, {'movie': movie})


def delete(request, id):
    if request.method == "POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST"  enctype="multipart/form-data">
  {% csrf_token %}
   <input type="text" name="name1" placeholder="Enter the movie name">
   <input type="text" name="name2" placeholder="desc">
   <input type="date" name="name3" placeholder="Enter the year">
   <input type="file" name="img">
   <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel ="stylesheet" href="{% static 'style.css' %}">
</head>
<style>
    body {
         background-color : aqua;
         }
</style>
<body>
<nav class="navbar sticky-bottom bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Movie Store</a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this movie?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{cini.img.url}}" height="300px" width="300px">
        </div>
<div class ="col-md-6">
        <h6>{{cini.name}}</h6><br>
         <h6>{{cini.desc}}</h6><br>
          <h6>{{cini.year}}</h6><br>
<a class="btn btn-warning" href = "{% url 'movieapp:update' cini.id %}">Update</a>
<a class="btn btn-danger" href = "{% url 'movieapp:delete' cini.id %}">Delete</a>
{% endblock %}

movieproject/templates/edit.html
<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="100px" width="100px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go Somewhere</a>
  </div>
           </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}